// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package zfs

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type mithrilZfsZfsSnapshot struct {
	_              structs.HostLayout
	ReadsInflight  uint64
	WritesInflight uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	mithrilZfsMapZfsIoSnapshot          = "zfs_io_snapshot"
	mithrilZfsProgKprobeZfsReadEntry    = "kprobe_zfs_read_entry"
	mithrilZfsProgKprobeZfsWriteEntry   = "kprobe_zfs_write_entry"
	mithrilZfsProgKretprobeZfsReadExit  = "kretprobe_zfs_read_exit"
	mithrilZfsProgKretprobeZfsWriteExit = "kretprobe_zfs_write_exit"
)

// loadMithrilZfs returns the embedded CollectionSpec for mithrilZfs.
func loadMithrilZfs() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MithrilZfsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load mithrilZfs: %w", err)
	}

	return spec, err
}

// loadMithrilZfsObjects loads mithrilZfs and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*mithrilZfsObjects
//	*mithrilZfsPrograms
//	*mithrilZfsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadMithrilZfsObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadMithrilZfs()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// mithrilZfsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type mithrilZfsSpecs struct {
	mithrilZfsProgramSpecs
	mithrilZfsMapSpecs
	mithrilZfsVariableSpecs
}

// mithrilZfsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type mithrilZfsProgramSpecs struct {
	KprobeZfsReadEntry    *ebpf.ProgramSpec `ebpf:"kprobe_zfs_read_entry"`
	KprobeZfsWriteEntry   *ebpf.ProgramSpec `ebpf:"kprobe_zfs_write_entry"`
	KretprobeZfsReadExit  *ebpf.ProgramSpec `ebpf:"kretprobe_zfs_read_exit"`
	KretprobeZfsWriteExit *ebpf.ProgramSpec `ebpf:"kretprobe_zfs_write_exit"`
}

// mithrilZfsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type mithrilZfsMapSpecs struct {
	ZfsIoSnapshot *ebpf.MapSpec `ebpf:"zfs_io_snapshot"`
}

// mithrilZfsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type mithrilZfsVariableSpecs struct {
}

// mithrilZfsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadMithrilZfsObjects or ebpf.CollectionSpec.LoadAndAssign.
type mithrilZfsObjects struct {
	mithrilZfsPrograms
	mithrilZfsMaps
	mithrilZfsVariables
}

func (o *mithrilZfsObjects) Close() error {
	return _MithrilZfsClose(
		&o.mithrilZfsPrograms,
		&o.mithrilZfsMaps,
	)
}

// mithrilZfsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadMithrilZfsObjects or ebpf.CollectionSpec.LoadAndAssign.
type mithrilZfsMaps struct {
	ZfsIoSnapshot *ebpf.Map `ebpf:"zfs_io_snapshot"`
}

func (m *mithrilZfsMaps) Close() error {
	return _MithrilZfsClose(
		m.ZfsIoSnapshot,
	)
}

// mithrilZfsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadMithrilZfsObjects or ebpf.CollectionSpec.LoadAndAssign.
type mithrilZfsVariables struct {
}

// mithrilZfsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadMithrilZfsObjects or ebpf.CollectionSpec.LoadAndAssign.
type mithrilZfsPrograms struct {
	KprobeZfsReadEntry    *ebpf.Program `ebpf:"kprobe_zfs_read_entry"`
	KprobeZfsWriteEntry   *ebpf.Program `ebpf:"kprobe_zfs_write_entry"`
	KretprobeZfsReadExit  *ebpf.Program `ebpf:"kretprobe_zfs_read_exit"`
	KretprobeZfsWriteExit *ebpf.Program `ebpf:"kretprobe_zfs_write_exit"`
}

func (p *mithrilZfsPrograms) Close() error {
	return _MithrilZfsClose(
		p.KprobeZfsReadEntry,
		p.KprobeZfsWriteEntry,
		p.KretprobeZfsReadExit,
		p.KretprobeZfsWriteExit,
	)
}

func _MithrilZfsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed mithrilzfs_bpfel.o
var _MithrilZfsBytes []byte
